# Generated by Django 3.0.5 on 2020-05-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersProfile', '0019_auto_20200519_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('female', 'FEMALE'), ('male', 'MALE')], default='male', max_length=20),
        ),
    ]
