# Generated by Django 3.0.5 on 2020-05-27 05:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usersProfile', '0020_auto_20200527_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='child_age',
        ),
        migrations.AddField(
            model_name='child',
            name='date_of_birth',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
