# Generated by Django 3.0.5 on 2020-05-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersProfile', '0021_auto_20200527_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('female', 'FEMALE'), ('male', 'MALE')], default='male', max_length=20),
        ),
    ]
