# Generated by Django 3.0.5 on 2020-05-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersProfile', '0022_auto_20200527_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='child_age',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
