# Generated by Django 3.0.5 on 2020-05-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersProfile', '0025_auto_20200527_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='child_date_of_birth',
        ),
        migrations.AddField(
            model_name='child',
            name='date_of_birth',
            field=models.CharField(default='5/5/15', max_length=20),
            preserve_default=False,
        ),
    ]
