# Generated by Django 3.0.5 on 2020-04-14 04:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersProfile', '0002_derived'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='derived',
            new_name='child',
        ),
    ]
