# Generated by Django 3.0.5 on 2020-05-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersProfile', '0003_notification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_description',
            field=models.CharField(default='dfdfdfdfdF', max_length=1000),
            preserve_default=False,
        ),
    ]
