# Generated by Django 3.0.5 on 2020-04-14 04:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersProfile', '0003_auto_20200414_1652'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='extendedusers',
            new_name='extendeduser',
        ),
    ]
