# Generated by Django 3.0.5 on 2020-04-14 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersProfile', '0004_auto_20200414_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name_plural': 'Child'},
        ),
        migrations.AlterModelOptions(
            name='extendeduser',
            options={'verbose_name_plural': 'ExtenderUser'},
        ),
    ]
