# Generated by Django 3.0.5 on 2020-05-08 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersProfile', '0006_auto_20200508_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='teacher_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
