# Generated by Django 3.0.5 on 2020-05-13 01:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usersProfile', '0008_auto_20200509_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(default='abc@abc.com', max_length=254),
            preserve_default=False,
        ),
    ]
