# Generated by Django 3.0.5 on 2020-04-15 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersProfile', '0009_auto_20200415_0430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extendeduser',
            options={'verbose_name_plural': 'ExtendedUser'},
        ),
        migrations.AddField(
            model_name='child',
            name='parent_id',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child',
            name='parent_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
