# Generated by Django 3.0.5 on 2020-05-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersProfile', '0009_auto_20200513_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='teacher_name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
