# Generated by Django 3.0.5 on 2020-04-16 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersProfile', '0010_auto_20200415_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='child',
            name='address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child',
            name='child_age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child',
            name='date_of_birth',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child',
            name='enrolment_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('female', 'FEMALE'), ('male', 'MALE')], default='male', max_length=20),
        ),
        migrations.AddField(
            model_name='child',
            name='guardian',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child',
            name='nationality',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child',
            name='relation_guardian',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
