# Generated by Django 3.0.5 on 2020-05-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersProfile', '0010_auto_20200513_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_DateTime',
            field=models.DateField(),
        ),
    ]
