# Generated by Django 3.0.5 on 2020-05-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersProfile', '0011_auto_20200518_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_duration',
        ),
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('female', 'FEMALE'), ('male', 'MALE')], default='male', max_length=20),
        ),
    ]
