# Generated by Django 3.0.5 on 2020-05-27 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersProfile', '0022_auto_20200527_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('female', 'FEMALE'), ('male', 'MALE')], default='male', max_length=20),
        ),
        migrations.AlterField(
            model_name='child',
            name='guardian_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usersProfile.guardian'),
        ),
    ]
