# Generated by Django 3.0.5 on 2020-05-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersProfile', '0023_auto_20200527_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='activity_DateTime',
            new_name='activity_Date',
        ),
        migrations.AlterField(
            model_name='child',
            name='date_of_birth',
            field=models.DateField(max_length=20),
        ),
    ]
